export {
  PatientsShell,
  PatientsShellCard,
  PatientsShellHeader,
  PatientsShellInputPanel,
  PatientsShellLocale,
  PatientsShellLocalePlaceholder,
  PatientsShellMain,
  PatientsShellMainDesktop,
  PatientsShellProgress,
  patientsFieldGroupClassName,
  patientsShellCardClassName,
  patientsShellClassName,
  patientsShellDesktopContentClassName,
  patientsShellHeaderClassName,
  patientsShellInputPanelClassName,
  patientsShellMainClassName,
  patientsShellMainDesktopClassName,
} from "./patients-shell";
